version: '3'
services:
  user-app:
    image: user-app
    build: MovieCruiserAuthenticationService/
    restart: always
    network_mode: host
    ports:
    - 8089:8089
    expose:
    - 8089
    depends_on:
    - movie-mysql 
  movie-app:
    image: movie-app
    build: MovieCruiserService/
    restart: always
    network_mode: host
    ports:
    - 8082:8082
    expose:
    - 8082
    depends_on:
    - movie-mysql
  movie-mysql:
    image: mysql:5.5
    build: Mysql_data/
    network_mode: host
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: root
      MYSLQ_PASSWORD: root123
      MYSQL_DATABASE: movieDb
  angular:
    image: angular-app
    build: FrontendAuth/
    network_mode: host
    container_name: angular-docker
    ports:
      - 4200:4200
