version: '3'
services:
  user-app:
    image: user-app
    build: MovieCruiserAuthenticationService/
    restart: always
    network_mode: host
    ports:
    - 8088:8088
    expose:
    - 8088
    depends_on:
    - movie-mysql
    - eureka-app
    - configserver-app
  movie-app:
    image: movie-app
    build: MovieCruiserService/
    restart: always
    network_mode: host
    ports:
    - 8087:8087
    expose:
    - 8087
    depends_on:
      - movie-mysql
      - eureka-app
      - configserver-app
  movie-mysql:
    image: mysql:5.5
    build: Mysql_data/
    network_mode: host
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: root
      MYSLQ_PASSWORD: root123
      MYSQL_DATABASE: movieDb
  eureka-app:
    image: eureka-app
    build: MovieCruiserEurekaServer/
    restart: always
    network_mode: host
    ports:
      - 9002:9002
    expose:
      - 9002
  configserver-app:
    image: configserver-app
    build: MovieCruiserConfigServer/
    restart: always
    network_mode: host
    ports:
      - 8081:8081
    expose:
      - 8081
    depends_on:
      - eureka-app
  apigateway-app:
    image: apigateway-app
    build: MovieCruiserZuulService/
    restart: always
    network_mode: host
    ports:
      - 8091:8091
    expose:
      - 8091
    depends_on:
      - eureka-app
      - configserver-app
      - movie-app
      - user-app
#  angular:
#    image: angular-app
#    build: FrontendAuth/
#    network_mode: host
#    container_name: angular-docker
#    ports:
#      - 4200:4200
