spring:
  application:
    name: zuul-service
server:
  port: 8091
eureka:
  client:
    service-url:
      defautlZone: http://localhost:9002/eureka
    register-with-eureka: true
    fetch-registry: true
zuul:
  routes:
    auth-service:
      url:  http://localhost:8088
    movie-service :
      url: http://localhost:8087
      sensitiveHeaders: Cookie,Set-Cookie


